apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "elasti.fullname" . }}-elastiservice-editor-role
  labels:
  {{- include "elasti.labels" . | nindent 4 }}
rules:
- apiGroups:
  - elasti.truefoundry.io
  resources:
  - elastiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasti.truefoundry.io
  resources:
  - elastiservices/status
  verbs:
  - get