apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasti.fullname" . }}-resolver-service
  labels:
  {{- include "elasti.labels" . | nindent 4 }}
spec:
  type: {{ .Values.resolverService.type }}
  selector:
    app: resolver
  {{- include "elasti.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.resolverService.ports | toYaml | nindent 2 }}