apiVersion: elasti.elasti.truefoundry.com/v1alpha1
kind: ElastiService
metadata:
  labels:
    app.kubernetes.io/name: elastiservice
    app.kubernetes.io/instance: elastiservice-sample
    app.kubernetes.io/part-of: elasti-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: elasti-operator
  name: elastiservice-sample
spec:
  # TODO(user): Add fields here
