apiVersion: elasti.truefoundry.com/v1alpha1
kind: ElastiService
metadata:
  labels:
    app.kubernetes.io/name: elasti-operator
    app.kubernetes.io/managed-by: kustomize
  name: emotion-class
  namespace: raman-ws
spec:
  queueTimeout: 4
  idlePeriod: 20
  service: emotion-class-svc
  deploymentName: emotion-class-svc
  minTargetReplicas: 1
  # scaleTargetRef:
  #   apiVersion: apps/v1
  #   kind: Rollouts
  #   name: emotion-class-svc
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployments
    name: emotion-class-svc

