apiVersion: elasti.truefoundry.com/v1alpha1
kind: ElastiService
metadata:
  labels:
    app.kubernetes.io/name: elasti-operator
    app.kubernetes.io/managed-by: kustomize
  name: httpbin-hello
  namespace: raman-ws
spec:
  minTargetReplicas: 0
  service: httpbin-hello
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: rollouts
    name: httpbin-hello

