apiVersion: elasti.truefoundry.com/v1alpha1
kind: ElastiService
metadata:
  labels:
    app.kubernetes.io/name: elasti-operator
    app.kubernetes.io/managed-by: kustomize
  name: emotion-class-elasti-service
  namespace: raman-ws
spec:
  minTargetReplicas: 2
  service: emotion-class-svc
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: rollouts
    name: emotion-class-svc

