# permissions for end users to edit elastiservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: elastiservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: elasti-operator
    app.kubernetes.io/part-of: elasti-operator
    app.kubernetes.io/managed-by: kustomize
  name: elastiservice-editor-role
rules:
- apiGroups:
  - elasti.elasti.truefoundry.com
  resources:
  - elastiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasti.elasti.truefoundry.com
  resources:
  - elastiservices/status
  verbs:
  - get
