---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - elasti.elasti.truefoundry.com
  resources:
  - elastiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasti.elasti.truefoundry.com
  resources:
  - elastiservices/finalizers
  verbs:
  - update
- apiGroups:
  - elasti.elasti.truefoundry.com
  resources:
  - elastiservices/status
  verbs:
  - get
  - patch
  - update
