apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasti-resolver-additional-access
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list", "watch", "update", "patch", "delete", "create"]