apiVersion: apps/v1
kind: Deployment
metadata:
  name: resolver
  namespace: elasti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resolver 
  template:
    metadata:
      labels:
        app: resolver 
    spec:
      containers:
      - name: playground
        image: localhost:5001/resolver:latest
        env:
        - name: SYSTEM_NAMESPACE
          value: elasti
        ports:
        - containerPort: 8012
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"  
          limits:
            memory: "1Gi"
            cpu: "750m"  

