apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: elasti-resolver
  name: elasti-resolver-service
  namespace: elasti
spec:
  selector:
    app: elasti-resolver
  ports:
  - name: http-playground
    protocol: TCP
    port: 8012
  type: LoadBalancer