# permissions for end users to view elastiservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: elasti-operator
    app.kubernetes.io/managed-by: kustomize
  name: elastiservice-viewer-role
rules:
- apiGroups:
  - elasti.truefoundry.com
  resources:
  - elastiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasti.truefoundry.com
  resources:
  - elastiservices/status
  verbs:
  - get
