# permissions for end users to edit elastiservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: elasti-operator
    app.kubernetes.io/managed-by: kustomize
  name: elastiservice-editor-role
rules:
- apiGroups:
  - elasti.truefoundry.io
  resources:
  - elastiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasti.truefoundry.io
  resources:
  - elastiservices/status
  verbs:
  - get
