apiVersion: v1
kind: Service
metadata:
  name: resolver-service
  namespace: elasti
spec:
  ports:
  - name: http-playground
    port: 8012
    protocol: TCP
  selector:
    app: elasti-resolver
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasti-resolver
  namespace: elasti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasti-resolver
  template:
    metadata:
      labels:
        app: elasti-resolver
    spec:
      containers:
      - env:
        - name: SYSTEM_NAMESPACE
          value: elasti
        image: ramantehlan/elasti-resolver:v1alpha1
        imagePullPolicy: Always
        name: playground
        ports:
        - containerPort: 8012
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 500Mi
