apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 labels:
   group: elasti
 name: elasti-operator-metrics-monitor
 namespace: elasti-operator-system
spec:
 endpoints:
   - path: /metrics
     port: custom-port
     scheme: http
 selector:
   matchLabels:
     control-plane: controller-manager
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    group: elasti
  name: elasti-resolver-metrics-monitor
  namespace: elasti
spec:
  endpoints:
    - port: http-playground
      path: /metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: elasti-resolver

