apiVersion: v1
kind: Service
metadata:
  name: target-service
  namespace: default
spec:
  selector:
    app: target 
  ports:
  - name: http-target-2
    protocol: TCP
    port: 8014
  type: LoadBalancer

