apiVersion: v1
kind: Service
metadata:
  name: controller-service
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: elasti-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013
      name: custom-port
