apiVersion: apps/v1
kind: Deployment
metadata:
  name: target
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target
  template:
    metadata:
      labels:
        app: target 
    spec:
      containers:
      - name: elasti-target
        image: localhost:5001/target:latest
        ports:
        - containerPort: 8014
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"  
          limits:
            memory: "1Gi"
            cpu: "750m"  
---
apiVersion: v1
kind: Service
metadata:
  name: target-service-pvt
  namespace: default
spec:
  selector:
    app: target
  ports:
  - name: http-target
    protocol: TCP
    port: 8014
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: target-service
  namespace: default
spec:
  selector:
    app: target 
  ports:
  - name: http-target-2
    protocol: TCP
    port: 8014
  type: LoadBalancer
---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#  name: target-service-hpa
#  namespace: default
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: target
#  maxReplicas: 13
#  targetCPUUtilizationPercentage: 80

