controllerManager:
  manager:
    args:
    - --leader-elect
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: localhost:5001/elasti-operator
      tag: v1alpha1
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
controllerService:
  ports:
  - name: custom-port
    port: 8013
    protocol: TCP
    targetPort: 8013
  type: ClusterIP
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
