apiVersion: apps/v1
kind: Deployment
metadata:
  name: activator
  namespace: elasti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activator 
  template:
    metadata:
      labels:
        app: activator 
    spec:
      containers:
      - name: elasti-activator
        image: localhost:5000/activator:latest
        env:
        - name: SYSTEM_NAMESPACE
          value: default
        - name: POD_NAME
          value: target
        - name: POD_IP
          value: http://target-pvt-service.default.svc.cluster.local:8014
        ports:
        - containerPort: 8012
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"  
          limits:
            memory: "1Gi"
            cpu: "750m"  
---
apiVersion: v1
kind: Service
metadata:
  name: activator-service
  namespace: elasti
spec:
  selector:
    app: activator
  ports:
  - name: http-activator
    protocol: TCP
    port: 8012
  type: LoadBalancer

