name: Push image to to JFROG Public

on:
  push:
    branches:
      - 'main'
    paths:
      - 'operator/**'
      - 'resolver/**'

permissions:
  id-token: write
  contents: read

env:
  IMAGE_TAG: ${{ github.sha }}
  ARTIFACTORY_USERNAME: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_PASSWORD }}
  ARTIFACTORY_REPOSITORY_URL: ${{ env.TRUEFOUNDRY_ARTIFACTORY_PUBLIC_REPOSITORY }}/${{ matrix.repository }}

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
        matrix:
          include:
            - directory: operator
              repository: elasti-operator
            - directory: resolver
              repository: elasti-resolver
    steps:
      - name: Checkoutout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v3
        with:
          username: ${{ env.ARTIFACTORY_USERNAME }}
          password: ${{ env.ARTIFACTORY_PASSWORD }}
          registry: tfy.jfrog.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.directory }}/Dockerfile
          push: true
          tags: ${{ env.ARTIFACTORY_REPOSITORY_URL }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.ARTIFACTORY_REPOSITORY_URL }}:buildcache
          cache-to: mode=max,image-manifest=true,type=registry,ref=${{ env.ARTIFACTORY_REPOSITORY_URL }}:buildcache
