name: Push image to to JFROG Public

on:
  push:
    branches:
      - 'main'
    paths:
      - 'operator/**'
      - 'resolver/**'

permissions:
  id-token: write
  contents: read

env:
  JFROG_REGISTRY: tfy.jfrog.io
  JFROG_PROJECT: tfy-images
  REPOSITORY: ${{ matrix.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
        matrix:
          include:
            - directory: operator
              repository: elasti-operator
            - directory: resolver
              repository: elasti-resolver
    steps:
      - name: Checkoutout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.JFROG_INTERNAL_USERNAME }}
          password: ${{ secrets.JFROG_INTERNAL_PASSWORD }}
          registry: tfy.jfrog.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          REGISTRY: ${{ env.JFROG_REGISTRY }}
          REGISTRY_ALIAS: ${{ env.JFROG_REPOSITORY }}
          REPOSITORY: ${{ matrix.repository }}
          IMAGE_TAG: ${{ github.sha }}
        with:
          file: ${{ matrix.directory }}/Dockerfile
          push: true
          tags: ${{ env.JFROG_REGISTRY }}/${{ env.JFROG_PROJECT }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.JFROG_REGISTRY }}/${{ env.JFROG_PROJECT }}/${{ env.REPOSITORY }}:buildcache
          cache-to: mode=max,image-manifest=true,type=registry,ref=${{ env.JFROG_REGISTRY }}/${{ env.JFROG_PROJECT }}/${{ env.REPOSITORY }}:buildcache
