name: Go Lint and Format with gopls

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  gopls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22' # specify your Go version here

      - name: Install gopls
        run: go install golang.org/x/tools/gopls@latest

      - name: Run gopls checks
        run: |
          gopls check ./operator/...
          gopls check ./resolver/...

      - name: Verify gofmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "The following files are not formatted:"
            gofmt -l .
            exit 1
          fi

      - name: Verify golint
        run: |
          go install golang.org/x/lint/golint@latest
          golint check ./operator/...
          golint check ./resolver/...
